### ISSUE TITLE
Error of Alberon's Warpath in 3.17

### ISSUE THREAD

**Issue by ShanyuenHK** [rChinnnn/rchin-poe-trade#71] opened 2022-02-09 18:33 UTC
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item name"}}
```
物品種類: 鞋子(Boots)
Rarity: 傳奇
阿爾貝隆的征途(Alberon's Warpath)
戰士之靴(Soldier Boots)
--------
護甲: 299 (augmented)
能量護盾: 19
--------
需求:
等級: 49
力量: 47
智慧: 47
--------
插槽: R-G R 
--------
物品等級: 67
--------
增加 15% 力量
攻擊附加 1 至 80 混沌傷害
+207 點護甲
+11% 混沌抗性
增加 20% 移動速度
+1 最大骷髏數量
--------
阿爾貝隆踱向詛咒之淵，
而那狐群狗黨露出巴結的嘴臉
```

**Comment by rChinnnn** [comment] 2022-02-10 00:55
Duplicate of #72

**Closed by rChinnnn** 2022-02-10 00:55 UTC
