### ISSUE TITLE
有問題ㄉ

### ISSUE THREAD

**Issue by abow0208** [rChinnnn/rchin-poe-trade#73] opened 2022-02-10 04:06 UTC
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item name"}}
```
物品種類: 戒指(Rings)
Rarity: 傳奇
瑪拉凱的巧技(Malachai's Artifice)
潛能之戒(Unset Ring)
--------
需求:
等級: 5
--------
插槽: W 
--------
物品等級: 72
--------
有 1 個插槽 (implicit)
--------
所有插槽都是白色
此物品插槽中寶石額外獲得元素之相
-20% 全部元素抗性
插上 1 個紅色寶石時獲得 +83% 火焰抗性
插上 1 個綠色寶石時獲得 +89% 冰冷抗性
插上 1 個藍色寶石時獲得 +92% 閃電抗性
--------
聆聽風之低語，順應風勢而行。
若是不願臣服，烈風轉眼而至。
```

**Comment by rChinnnn** [comment] 2022-02-10 08:58
Duplicate of #72

**Closed by rChinnnn** 2022-02-10 08:58 UTC
